stages:
  - test
  - deploy

variables:
  DBT_PROFILES_DIR: $CI_PROJECT_DIR/.dbt

test_dbt:
  stage: test
  image: python:3.12
  before_script:
    - pip install uv
    - uv sync
    - mkdir -p $DBT_PROFILES_DIR
    - |
      cat << EOF > $DBT_PROFILES_DIR/profiles.yml
      bytebuddies:
        target: dev
        outputs:
          dev:
            type: duckdb
            path: $CI_PROJECT_DIR/data/bytebuddies.duckdb
            external_root: $CI_PROJECT_DIR/data/raw
      EOF
  script:
    - cd dbt
    - uv run dbt debug
    - uv run dbt build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  image: squidfunk/mkdocs-material
  script:
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  pages: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH