pages:
  stage: deploy
  image: squidfunk/mkdocs-material
  script:
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  pages: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH