image: python:3.12

default:
  before_script:
    - pip install uv
    - uv sync

pages:
  script:
    - uv run mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
