bytebuddies_dbt:
  outputs:
    dev:
      type: duckdb
      path: '../data/warehouse/dev.duckdb'
      external_root: '../data/pbi_prototypes'
      extensions:
        - httpfs
        - parquet
      threads: 1
  target: dev
